//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtomasyonu.Others
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalisanBilgileri
    {
        public int Calisan_Id { get; set; }
        public string Calisan_Adi { get; set; }
        public string Calisan_Soyadi { get; set; }
        public string Calisan_Tc { get; set; }
        public string Calisan_Cinsiyeti { get; set; }
        public string Calisan_KullaniciAdi { get; set; }
        public string Calisan_Sifre { get; set; }
        public string Calisan_TelNo { get; set; }
        public string Calisan_Eposta { get; set; }
        public string Calisan_Adres { get; set; }
        public Nullable<System.DateTime> Calisan_LastLogin { get; set; }
        public Nullable<System.DateTime> Calisan_EklenmeTarihi { get; set; }
    }
}
