//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtomasyonu.Others
{
    using System;
    using System.Collections.Generic;
    
    public partial class KitapBilgileri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KitapBilgileri()
        {
            this.KiralıkBilgileri = new HashSet<KiralıkBilgileri>();
        }
    
        public int Kitap_Id { get; set; }
        public string Kitap_ISBN { get; set; }
        public string Kitap_Adi { get; set; }
        public string Kitap_Yazari { get; set; }
        public string Kitap_Dili { get; set; }
        public string Kitap_SayfaSayisi { get; set; }
        public string Kitap_BasimYili { get; set; }
        public string Kitap_YayinEvi { get; set; }
        public string Kitap_Cevirmen { get; set; }
        public string K_OduncDurumu { get; set; }
        public Nullable<System.DateTime> Kitap_EklenmeTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KiralıkBilgileri> KiralıkBilgileri { get; set; }
    }
}
