//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtomasyonu.Others
{
    using System;
    using System.Collections.Generic;
    
    public partial class KiralıkBilgileri
    {
        public int Kirala_Id { get; set; }
        public int Kitap_Id { get; set; }
        public int Uye_Id { get; set; }
        public System.DateTime Kiralama_Tarihi { get; set; }
        public System.DateTime Teslim_Tarihi { get; set; }
        public Nullable<int> Kalan_Gun { get; set; }
    
        public virtual KitapBilgileri KitapBilgileri { get; set; }
        public virtual UyeBilgileri UyeBilgileri { get; set; }
    }
}
