//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtomasyonu.Others
{
    using System;
    using System.Collections.Generic;
    
    public partial class OdemeBilgileri
    {
        public int Odeme_Id { get; set; }
        public string Odeme_No { get; set; }
        public Nullable<int> Uye_Id { get; set; }
        public Nullable<int> Odenen_Tutar { get; set; }
        public Nullable<System.DateTime> Odeme_Tarihi { get; set; }
    
        public virtual UyeBilgileri UyeBilgileri { get; set; }
    }
}
